### ISSUE TITLE
Thank you for this theme

### ISSUE THREAD

**Issue by DealsBeam** [opdev1004/op-blogger-themes#23]
I am using your theme on my blogspot, but posts are not showing up

**Comment by opdev1004** [comment]
Can you tell me more details? Like where it does not show posts?

If you are talking about 'Homepage', right now blogger has pagination bug.

And this bug cannot be fixed as I am only able to fix what blogger theme allows me to use.

So I added a html widget that we can write a homepage content for none-devlopers instead of showing list of post or single post.

If you want other behaviour, remove html widget and just write/fix a homepage content within Blog1 widget in blogger theme's html edit.

```
<b:if cond='data:view.isHomepage'>
some homepage content
</b:if>
```
or find ```not data:view.isHomepage``` and fix them to show content.

=========

\+ Make sure follow installation instruction.

1. Apply a Contempo theme first.
2. Copy and paste theme code into the html theme editor. Or you can try use restore button too.

Because if base theme is different, theme does not work.

**Comment by opdev1004** [comment]
No reply for long time so I close this issue
